version: '3.3'

services:
  app:
    image: client
    container_name: client
    build: . #Hace el build utilizando el Dockerfile
    ports: 
      - 80:3000
    environment:
      - MONGO_URI=mongodb://mongo_db/sample
    depends_on: 
      - db
    networks: 
      - net3
  db:
    image: mongo:3.0.15
    container_name: mongo_db
    volumes:
      - ./db:/data/db
    networks:
      net3:
        aliases:
          - "mongo_db" #Nombre alternativo para llamarlo dentro de esta red
        ipv4_address: 172.16.238.10 #IP fija
        ipv6_address: 2001:3984:3989::10 #IP Fija
networks: #Configuracion de la red que utilizamos
  net3:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 172.16.238.0/24
      -
        subnet: 2001:3984:3989::/64