version: '3.2'
services:
 web:
  image: nginx:alpine
  volumes:
   - type: volume
     source: data
     target: /data1
     volume:
      nocopy: true
   - type: bind
     source: ./static
     target: /opt/app/static
  ports:
   - 80:80
 db:
  image: postgres:latest
  volumes:
   - "/var/run/postgres/postgres.sock:/var/run/postgres.sock"
   - "dbdata:/var/lib/postgresql/data"

volumes:
 data:
 dbdata: